name: Release

on:
  push:
    branches:
      - main
      - feat/*

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1.4.1
        with:
          version: 1.8.3
          virtualenvs-in-project: true

  test:
    needs: setup
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run tests
        run: poetry run pytest

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: poetry install
      - name: Semantic Version Release
        id: release
        uses: python-semantic-release/python-semantic-release@v8.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        uses: python-semantic-release/publish-action@v9.14.0
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
